frontend/ios/Podfile.lock, frontend/lib/features/home/home_page.dart, frontend/lib/features/pfis/pfi_providers.dart, frontend/lib/features/pfis/pfi_verification_page.dart, frontend/pubspec.lock, frontend/pubspec.yaml
Uses a mock PFI verification widget for now `https://robustdisastrousstartups.wesbillman.repl.co/?proof=moeisreal&callback_uri=didpay://wes`
=> feat: add mock pfi verification widget

frontend/lib/features/home/home_page.dart, frontend/lib/features/pfis/pfi_confirmation_page.dart, frontend/lib/features/pfis/pfi_providers.dart, frontend/lib/features/send/send_page.dart, frontend/lib/shared/number_pad.dart
Created on-screen number pad to be used for input fields requiring number input. `SendPage` was added to show the functionality of the number pad. 
Note: the increased font size animation is made to stop only when the user lets go of the key press
https://github.com/TBD54566975/didpay/assets/125412902/84d30d86-7736-4a4a-ad10-ee67f397c9fd
https://github.com/TBD54566975/didpay/assets/125412902/e71d3ff3-60dc-4199-8900-d99270a05cf1
=> feat: add on-screen number pad

frontend/lib/features/app/app_tabs.dart, frontend/lib/features/home/account_balance.dart, frontend/lib/features/home/home_page.dart, frontend/lib/l10n/app_en.arb, frontend/lib/l10n/app_localizations.dart, frontend/lib/l10n/app_localizations_en.dart, frontend/lib/shared/theme/color_scheme.dart, frontend/test/features/app/app_tabs_test.dart, frontend/test/features/home/account_balance_test.dart
Implemented account balance widget containing the balance, and buttons to deposit and withdraw. `SendPage` was moved to its own tab in `AppTabs`
=> feat: add account balance widget

README.md, frontend/ios/Podfile.lock, frontend/lib/features/pfis/pfi_providers.dart, frontend/lib/features/pfis/pfis_page.dart, frontend/pubspec.lock, frontend/pubspec.yaml
This will load the PFIs from an open github repo, caching them: TBD54566975/pfi-providers-data
It even shows a spinny circle the first time it is loading, which is kind of neat. Great typo on the branch name.
=> load PFIs from known source and cache as shared preference

frontend/lib/features/deposit/deposit_page.dart, frontend/lib/features/home/transaction_details_page.dart, frontend/lib/features/withdraw/withdraw_page.dart, frontend/lib/l10n/app_en.arb, frontend/lib/l10n/app_localizations.dart, frontend/lib/l10n/app_localizations_en.dart, frontend/lib/shared/json_schema_form.dart, frontend/lib/shared/payment_details_page.dart, frontend/lib/shared/payment_method.dart, frontend/lib/shared/payment_methods_page.dart, frontend/lib/shared/search_payment_methods_page.dart, frontend/lib/shared/theme/theme.dart, frontend/test/shared/json_schema_form_test.dart, frontend/test/shared/payment_details_page_test.dart, frontend/test/shared/search_payment_methods_page_test.dart
closes https://github.com/TBD54566975/didpay/issues/39
uses a `SegmentedButton` at top to toggle different payment types (i.e. `bank` or `momo`) and implemented `SearchPaymentMethodsPage` to search for different payment subtypes (e.g. `MTN` or `MPESA`)
also uses `JsonSchemaForm` to build dynamic forms based on mock schemas dependent on the payment types
https://github.com/TBD54566975/didpay/assets/125412902/22a01d18-4485-4695-8c63-69cf7bb2ef37
https://github.com/TBD54566975/didpay/assets/125412902/855fb150-b4aa-4a5c-86b5-a77619df2794
=> feat: add payment details page

lib/features/payment/payment_details.dart, lib/features/payment/review_payment_page.dart, lib/features/tbdex/quote_notifier.dart, lib/features/tbdex/tbdex_exceptions.dart, lib/features/tbdex/tbdex_providers.dart, lib/l10n/app_en.arb, lib/l10n/app_localizations.dart, lib/l10n/app_localizations_en.dart, lib/shared/http_status.dart, lib/shared/json_schema_form.dart, pubspec.lock, test/features/payin/payin_details_page_test.dart, test/features/payment/review_payment_page_test.dart, test/features/payout/payout_details_page_test.dart
on top of using the new response type from `TbdexHttpClient` that returns the status codes, this pr:
- ensures that rfq submission succeeds before attempting to poll for quotes
- adds a retry widget if quote polling fails
- adds http status class with extension functions
https://github.com/TBD54566975/didpay/assets/125412902/4d55d4f4-451d-4eb6-8aca-9a0f0b6e368b
=> feat: `TbdexHttpClient` improvements

lib/features/app/app.dart, lib/features/currency/currency_dropdown.dart, lib/features/currency/currency_modal.dart, lib/features/kcc/kcc_retrieval_page.dart, lib/features/kcc/kcc_webview_page.dart, lib/features/payin/payin.dart, lib/features/payment/payment_amount_page.dart, lib/features/payout/payout.dart, lib/features/tbdex/tbdex_service.dart, lib/shared/theme/grid.dart, test/features/home/home_page_test.dart, test/features/payin/payin_test.dart, test/features/payment/payment_amount_page_test.dart, test/features/payout/payout_test.dart
this pr allows multiple pfis to be supported within didpay, including:
- viewing all offerings from every pfi loaded in `My PFIs`
- making http requests to the pfi that hosts the offering selected in `PaymentAmountPage`
=> feat: support multiple pfis

lib/features/account/account_page.dart, lib/features/countries/countries_notifier.dart, lib/features/currency/currency_dropdown.dart, lib/features/kcc/kcc_retrieval_page.dart, lib/features/kcc/kcc_webview_page.dart, lib/features/modals/modal_select_currency.dart, lib/features/payin/payin.dart, lib/features/payment/payment_amount_page.dart, lib/features/payment/payment_review_page.dart, lib/features/payment/payment_state.dart, lib/features/payout/payout.dart, lib/features/pfis/add_pfi_page.dart, lib/features/tbdex/tbdex_service.dart, lib/main.dart, test/features/app/app_tabs_test.dart, test/features/home/home_page_test.dart, test/features/payin/payin_test.dart, test/features/payment/payment_amount_page_test.dart, test/features/payment/payment_details_page_test.dart, test/features/payment/payment_methods_page_test.dart, test/features/payment/payment_types_page_test.dart, test/features/payment/review_payment_page_test.dart, test/features/payout/payout_test.dart
- makes use of `PaymentState` across more widgets 
- uses `Decimal` across more widgets
- updates tests to reduce lines of code
=> chore: clean up

lib/features/countries/countries_page.dart, lib/features/kcc/kcc_consent_page.dart, lib/features/kcc/kcc_retrieval_page.dart, lib/features/payment/payment_amount_page.dart, lib/features/payment/payment_review_page.dart, lib/features/pfis/add_pfi_page.dart, lib/features/send/send_details_page.dart, lib/features/send/send_page.dart, lib/l10n/app_en.arb, lib/l10n/app_localizations.dart, lib/l10n/app_localizations_en.dart, lib/shared/async/async_data_widget.dart, lib/shared/async/async_error_widget.dart, lib/shared/json_schema_form.dart, lib/shared/next_button.dart, test/features/send/send_page_test.dart
this pr adds a shared `NextButton` widget to get rid of redundant `buildNextButton()` helper functions in every page
=> feat: add next button

lib/features/account/account_balance_card.dart, lib/features/account/account_page.dart, lib/features/countries/countries.dart, lib/features/countries/countries_notifier.dart, lib/features/countries/countries_page.dart, lib/features/feature_flags/feature_flag.dart, lib/features/feature_flags/feature_flags_notifier.dart, lib/features/feature_flags/lucid/lucid_offerings_page.dart, lib/features/home/home_page.dart, lib/features/payment/payment_amount_page.dart, lib/features/payment/payment_state.dart, lib/features/send/send_page.dart, lib/features/vcs/vcs_notifier.dart, lib/l10n/app_en.arb, lib/l10n/app_localizations.dart, lib/l10n/app_localizations_en.dart, lib/main.dart, test/features/account/account_page_test.dart, test/features/app/app_tabs_test.dart, test/features/app/app_test.dart, test/features/countries/countries_notifier_test.dart, test/features/feature_flags/feature_flags_notifier_test.dart, test/features/feature_flags/lucid/lucid_offerings_page_test.dart, test/features/payment/payment_amount_page_test.dart, test/features/send/send_page_test.dart, test/helpers/mocks.dart
- adds lucid mode: a developer setting to view every offering from all your pfis, regardless of if they are fully compatible with didpay
- adds `FeatureFlag` and `FeatureFlagsNotifier`
https://github.com/TBD54566975/didpay/assets/125412902/0b8f22b4-5b9e-4bdf-bf40-76a46c7dd840
=> feat: add lucid mode

lib/features/countries/countries_page.dart, lib/features/feature_flags/lucid/lucid_offerings_page.dart, lib/features/payment/payment_amount_page.dart, lib/features/payment/payment_details_page.dart, lib/features/tbdex/tbdex_service.dart, test/features/feature_flags/lucid/lucid_offerings_page_test.dart, test/features/home/home_page_test.dart, test/features/payment/payment_amount_page_test.dart
adds support for filtering offerings using `GetOfferingsFilter` from `tbdex-dart`
=> feat: filter offerings

ios/Runner/Info.plist, lib/features/payment/payment_link_webview_page.dart
* sniff out `finish.html` using `onLoadStop` instead of `onCloseWindow`
* allow http requests from mobile devices
=> smol fixes

lib/features/dap/dap_form.dart, lib/features/dap/dap_qr_tile.dart, lib/features/feature_flags/lucid/lucid_offerings_page.dart, lib/features/home/home_page.dart, lib/features/kcc/kcc_retrieval_page.dart, lib/features/kcc/kcc_webview_page.dart, lib/features/payment/payment_amount_page.dart, lib/features/payment/payment_details_page.dart, lib/features/payment/payment_link_webview_page.dart, lib/features/payment/payment_review_page.dart, lib/features/pfis/pfis_add_page.dart, lib/features/send/send_page.dart, lib/features/tbdex/tbdex_service.dart, lib/shared/modal/modal_remove_item.dart
- ensures that no `ValueNotifier` hooks are being updated after they have been unmounted
- removes uses of `then()`, especially in combination with `await`
- allow "popping" behavior when pressing back button after submitting rfq in `PaymentDetailsPage`
=> feat: async safety

lib/features/payment/payment_review_page.dart, test/helpers/test_data.dart
- fix check in `PaymentReviewPage` to navigate to `PaymentLinkWebviewPage` if payin link is found in quote
=> fix: open `PaymentLinkWebviewPage` if payin link found

lib/features/kcc/kcc_webview_page.dart
- fixes idv widget dismissal bug by looking for `finish.html` in widget url to push `KccRetrievalPage`
=> fix: look for `finish.html` in url

lib/features/feature_flags/lucid/lucid_offerings_page.dart, lib/features/home/home_page.dart, lib/features/kcc/kcc_retrieval_page.dart, lib/features/kcc/kcc_webview_page.dart
- adds check for mounted context before updating `ValueNotifier` hooks that are called after async calls such as fetching tbdex resources or sending tbdex messages
=> chore: add check for `context.mounted`

lib/features/payment/payment_amount_page.dart, lib/shared/number/number_display.dart
- adds check for null `payinAmount` to account for beginning state of `PayinAmountPage` input amount which fixes a glitch where the input amount would start at `0.` and then quickly switch to `0`
=> fix: add check for null `payinAmount`

lib/features/account/account_balance_card.dart, lib/features/payin/payin.dart, lib/features/payment/payment_amount_page.dart, lib/features/payout/payout.dart, lib/features/send/send_page.dart, lib/features/transaction/transaction.dart, lib/features/transaction/transaction_tile.dart, lib/shared/number/number_pad.dart, test/features/home/home_page_test.dart
- updates snackbar for transaction updates to be floating and to use `surface` background color instead of grey background color
- decreases size of feature flag icons
- makes `PaymentAmountPage` be more compact to accomodate for larger `NumberPad`
- hardcodes account balance to always say `0 USD`
=> feat: ui adjustments

lib/features/kcc/kcc_webview_page.dart, pubspec.lock
- sets `resizeToAvoidBottomInset` to false to fix bug where screen goes blank when focusing on a new input field
=> fix: prevent webview resizing

lib/features/kcc/kcc_consent_page.dart, lib/features/kcc/kcc_retrieval_page.dart
- checks for mounted context before exiting the `ModalFlow` which is responsible for all KCC pages
=> fix: check `context.mounted` before exiting `ModalFlow`

lib/features/payment/payment_link_webview_page.dart, lib/features/payment/payment_order_page.dart, lib/features/payment/payment_review_page.dart
- adds `PaymentOrderPage` to handle submitting the order
- update `PaymentLinkWebviewPage` to push to the `PaymentOrderPage` to stop using navigation pop and its associated pop animation
=> feat: update order handling

lib/features/payment/payment_details_page.dart, lib/features/payment/payment_order_page.dart, lib/features/payment/payment_quote_widget.dart, lib/features/payment/payment_review_page.dart, lib/features/payment/payment_state.dart, lib/features/transaction/transaction_tile.dart, test/features/payment/payment_review_page_test.dart
follow up pr to https://github.com/TBD54566975/didpay/pull/241
- adds `PaymentQuoteWidget` to handle polling for quote in `PaymentDetailsPage` to allow the `sending request` spinner to switch to `getting quote` without pushing to a new page
=> feat: add `PaymentQuoteWidget`

lib/features/kcc/kcc_retrieval_page.dart, lib/features/kcc/kcc_webview_page.dart
- this pr reroutes the `Tap to retry` button that appears when unable to retrieve a KCC in `KccRetrievalPage`
- restarts `KccWebviewPage` instead of re-polling for a KCC
=> fix: have retry for failed kcc restart idv widget

lib/features/account/account_balance_card.dart, lib/features/account/account_balance_notifier.dart, lib/features/tbdex/tbdex_service.dart, lib/features/transaction/transaction.dart, pubspec.lock, test/features/app/app_tabs_test.dart, test/features/app/app_test.dart, test/features/home/home_page_test.dart
- updates tbdex to include `OrderStatus` enums which were breaking `OrderStatus.fromJson`
- passes in `BearerDid` to account balance calls to allow for protected endpoint use: https://github.com/TBD54566975/tbdex/blob/main/specs/http-api/README.md#protected-endpoints
=> fix: update tbdex dep

lib/shared/modal/modal_flow.dart
attempts fix for black screen that occurs when popping from `KccRetrievalPage` back to `PaymentDetailsPage`
=> fix: remove `PopScope` from `ModalFlow`

lib/features/account/account_page.dart, lib/features/did/did_qr_code_page.dart, lib/features/did/did_storage_service.dart, lib/l10n/app_en.arb, lib/l10n/app_localizations.dart, lib/l10n/app_localizations_en.dart, lib/shared/modal/modal_manage_item.dart
following https://github.com/TBD54566975/didpay/pull/250, updates copy button to copy did uri
=> fix: update did copy

lib/shared/json_schema_form.dart
- allows form data in `JsonSchemaForm` to persist even across widget rebuilds
=> feat: persist form data

lib/features/payment/payment_review_page.dart, lib/features/tbdex/tbdex_service.dart, lib/l10n/app_en.arb, lib/l10n/app_localizations.dart, lib/l10n/app_localizations_en.dart, lib/shared/json_schema_form.dart, test/features/payment/payment_review_page_test.dart
this pr adds a confirmation dialog in `PaymentReviewPage` to alert the user that going back from that page means that quotes will have to be re-fetched
=> feat: add `ConfirmDialog` in `PaymentReviewPage`

lib/features/tbdex/tbdex_service.dart
- reduces added delay in `getOfferings()`, `sendRfq()`, and `sendOrder()` from 500 ms to 300 ms
- only return exchanges that contain a `OrderStatus` message in the exchange
=> chore: improve `TbdexService`

lib/features/payment/payment_details_page.dart, lib/shared/json_schema_form.dart, test/shared/json_schema_form_test.dart
this pr simplifies the `onSubmit()` callback in the `JsonSchemaForm` widget by making it async and cleaning up the credentials/rfq logic
=> chore: refactor `onSubmit()` callback in `JsonSchemaForm`

lib/features/dap/dap_form.dart, lib/features/send/send_page.dart
closes https://github.com/TBD54566975/didpay/issues/269
https://github.com/user-attachments/assets/f9001b6e-0e7f-4f00-a6c0-c32e62e3f200
=> fix: dap erased after typo

lib/shared/json_schema_form.dart
this pr fixes a UI bug where you could not reenter `PaymentDetailsPage` after re-selecting a payment method or payment type in `PaymentMethodsPage` or `PaymentTypesPage`
=> fix: reset `TextEditingController` to prevent use after disposal

lib/features/kcc/kcc_webview_page.dart
this pr checks for `finish.html` in the IDV request given from a PFI (as detailed in the [KCC spec](https://github.com/TBD54566975/known-customer-credential?tab=readme-ov-file#response-1)) and, if found, goes straight to `KccRetrievalPage` without loading any webview
=> feat: add support for no-op idv flow

lib/features/kcc/kcc_consent_page.dart, lib/features/kcc/kcc_issuance_service.dart, lib/features/kcc/kcc_webview_page.dart, lib/features/payment/payment_details_page.dart
this pr ensures that the `PresentationDefinition` id (found in the offering selected by the user) is used to initiate the KCC application via a query parameter `presentation_definition_id` as detailed in the [spec](https://github.com/TBD54566975/known-customer-credential?tab=readme-ov-file#request)
=> feat: use `PresentationDefinition` id to initiate KCC application

lib/features/dap/dap_state.dart, lib/features/payment/payment_amount_page.dart, lib/features/payment/payment_details_page.dart, lib/features/payment/payment_details_state.dart, lib/features/payment/payment_method.dart, lib/features/payment/payment_state.dart, lib/features/send/send_page.dart, lib/features/tbdex/tbdex_service.dart, lib/shared/json_schema_form.dart, test/features/home/home_page_test.dart, test/features/payment/payment_amount_page_test.dart
this pr adds a `DapState` which is used to support finding offerings specific to a dap's available money addresses and to autofill payment details based on the selected currency and associated money address.
=> feat: add `DapState`

lib/features/tbdex/tbdex_service.dart
this pr updates the temporary offerings filter on stored balance payin kinds to filter out `USD_STOREDBAL_PAYIN` instead of `STORED_BALANCE`
=> fix: change filter to look for `USD_STOREDBAL_PAYIN`

lib/features/payment/payment_details_page.dart
- this pr resets the quote `AsyncValue` in `PaymentDetailsPage` after exiting kcc flow without getting an issued credential
=> fix: reset quote async value

pubspec.lock, pubspec.yaml
this pr updates the `web5` dependency to `0.4.0` to allow for flutter web support by fixing the following error when running didpay on web
```
DartError: Unsupported operation: Int64 accessor not supported by dart2js.
```
=> chore: update to web5 `0.4.0`

lib/features/device/device_info_service.dart
Added a check for kIsWeb in the DeviceInfoService to bypass the `isPhysicalDevice()` check on web platforms, since the app doesn't support QR code scanning on the web. Now the method will return false when running on the web, avoiding the unsupported operation error that occurs when trying to run device checks.
- Imported `kIsWeb` to detect web platform.
- Updated isPhysicalDevice() to return false for the web platform.
- Ensured backward compatibility with iOS and Android platforms.
Closes #296
=> fix(web): prevent unsupported operation error in isPhysicalDevice() on web

lib/features/dap/dap_form.dart, lib/features/send/send_page.dart
This PR updates the `SendPage` to remove the "Verifying DAP..." loading message and show a loading spinner to the right of the DAP input form when resolving the DAP.
https://github.com/user-attachments/assets/fd701818-8ca4-4abf-af3e-ae4917d7a695
Closes #285
=> chore: remove 'verifying dap...' loading message from sendpage

test/features/account/account_balance_card_test.dart
This PR adds UI tests for the `AccountBalanceCard` widget.
Closes #286
=> test: add ui tests for `AccountBalanceCard`

test/helpers/test_data.dart
this pr adds `payoutCurrency` and `payoutCurrencies` as optional named parameters to the `TestData` methods `getOffering()` and `getOfferingsMap()`, respectively
=> chore: update `TestData`

test/features/transaction/transaction_tile_test.dart, test/helpers/mocks.dart, test/helpers/test_data.dart
This PR adds UI tests for the `TransactionTile` widget.
Closes #290.
=> test: add ui tests for `TransactionTile` widget

test/features/transaction/transaction_notifier_test.dart, test/helpers/mocks.dart
This PR adds UI tests for the `TransactionNotifier` class.
Closes #291.
=> test: add tests for `TransactionNotifier`

test/features/transaction/transaction_details_page_test.dart, test/features/transaction/transaction_tile_test.dart, test/helpers/mocks.dart
Hey @ethan-tbd  check out this pull request. Do let me know if there is anything to fix.
Transaction detail page test added.
closes #289
=> test: add tests for `TransactionDetailsPage`

test/features/account/account_balance_notifier_test.dart
This PR adds tests for the `AccountBalanceNotifier` class.
Closes #292.
=> test: add tests for `AccountBalanceNotifier`

test/features/dap/dap_form_test.dart
This PR adds UI tests for the `DapForm` widget. 
Closes #288
=> test: add ui tests for `DapForm` widget

test/features/tbdex/tbdex_quote_notifier_test.dart
This PR introduces several tests for `TbdexQuoteNotifier`.
closes #293
=> test: add tests for `TbdexQuoteNotifier`

test/features/tbdex/tbdex_order_instructions_notifier_test.dart, test/helpers/test_data.dart
This PR adds tests for the `TbdexOrderInstructionsNotifier` class.
Closes #294.
=> test: add tests for `TbdexOrderInstructionsNotifier`

lib/shared/modal/modal_select_currency.dart
this pr supports a `(KBC)` tag to offerings in the Select Currency modal to differentiate between KBC and KCC offerings
=> feat: add KBC offering tag
