- README.md
> update the README a bit

- frontend/test/features/account/account_did_page_test.dart
- frontend/test/helpers/mocks.dart
- frontend/test/shared/number_pad_test.dart
added tests for `NumberPad` and `AccountDidPage` widgets
> feat: add more widget tests

- frontend/lib/features/account/account_did_page.dart
- frontend/lib/features/account/account_vc_page.dart
- frontend/lib/features/home/account_balance.dart
- frontend/lib/features/onboarding/onboarding_welcome_page.dart
- frontend/lib/features/pfis/pfi_confirmation_page.dart
- frontend/lib/features/send/send_page.dart
- frontend/lib/shared/grid.dart
- frontend/lib/shared/number_pad.dart
closes https://github.com/TBD54566975/didpay/issues/13
> feat: add padding constants

- frontend/lib/features/app/app_tabs.dart
- frontend/lib/features/home/home_page.dart
- frontend/lib/features/home/transaction_details_page.dart
- frontend/lib/l10n/app_en.arb
- frontend/lib/l10n/app_localizations.dart
- frontend/lib/l10n/app_localizations_en.dart
- frontend/lib/shared/transaction.dart
- frontend/test/features/deposit/deposit_page_test.dart
- frontend/test/features/home/home_page_test.dart
- frontend/test/features/home/transaction_details_page_test.dart
- frontend/test/features/send/send_did_page_test.dart
- frontend/test/features/send/send_page_test.dart
- frontend/test/features/withdraw/withdraw_page_test.dart
closes https://github.com/TBD54566975/didpay/issues/34
https://github.com/TBD54566975/didpay/assets/125412902/6c362233-49ac-4ef3-98c8-bf0962ccda5d
https://github.com/TBD54566975/didpay/assets/125412902/704fa6b0-9081-4d36-aeb1-06e542a1fb1e
> feat: add transaction details page

- frontend/lib/features/home/transaction_details_page.dart
- frontend/lib/features/pfis/pfi_confirmation_page.dart
- frontend/lib/features/send/send_did_page.dart
- frontend/lib/l10n/app_en.arb
- frontend/lib/l10n/app_localizations.dart
- frontend/lib/l10n/app_localizations_en.dart
- frontend/lib/shared/success_page.dart
- frontend/test/shared/success_page_test.dart
closes https://github.com/TBD54566975/didpay/issues/36
note: we will likely have to put a verifying page before every success page, similar to what is done in the current vc flow. (tracked in https://github.com/TBD54566975/didpay/issues/43)
https://github.com/TBD54566975/didpay/assets/125412902/c6ef23f2-e1b0-4b21-921b-b873d468ad77
https://github.com/TBD54566975/didpay/assets/125412902/17cb0c52-f34f-43a1-be8b-a6fac0a3b4b0
https://github.com/TBD54566975/didpay/assets/125412902/c75c2f9d-f946-4701-9ab9-a4eada4d35c7
https://github.com/TBD54566975/didpay/assets/125412902/d96e8ed5-af10-4c4d-8e9b-a56f3bad3b6b
> feat: add success page

- lib/features/payments/search_payment_methods_page.dart
- lib/features/send/send_did_page.dart
- lib/shared/json_schema_form.dart
- lib/shared/theme/theme.dart
> chore: undo last two commits to main

- lib/features/payments/search_payment_methods_page.dart
- lib/features/send/send_did_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- lib/shared/json_schema_form.dart
- lib/shared/theme/theme.dart
- test/features/send/send_did_page_test.dart
> chore: update text fields

- lib/features/pfis/pfi_confirmation_page.dart
- lib/features/send/send_confirmation_page.dart
- lib/features/send/send_did_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- lib/shared/pending_page.dart
- lib/shared/success_page.dart
- test/features/send/send_confirmation_page_test.dart
- test/shared/pending_page_test.dart
closes #43 
https://github.com/TBD54566975/didpay/assets/125412902/7f3f4dbb-008f-4201-8b8f-e74a07f48254
https://github.com/TBD54566975/didpay/assets/125412902/3eab83a4-34b9-4357-b82e-c97b625206f6
> feat: add pending page

- lib/features/pfis/pfi_verification_page.dart
- lib/services/idv_service.dart
completes everything up to and including step 4 in [Initiating IDV Flow](https://github.com/tbdeng/known-customer-credential?tab=readme-ov-file#initiating-idv-flow)
> feat: construct SIOPv2 auth response

- lib/features/onboarding/agreement_page.dart
- lib/features/pfis/pfi_verification_page.dart
- lib/services/idv_service.dart
checkpoint for idv/kcc flow, added todos and fixed the widget url
> feat: start up idv widget

- lib/features/pfis/pfi_verification_page.dart
- lib/services/idv_service.dart
sometimes we're responsible adults! 
addresses todos related to adding try/catches and checking for null errors in `IdvService`
> fix: handle errors for idv

- lib/services/idv_service.dart
this was throwing me off. looks like `_getIdvRequest` is actually posting the auth response
> naming: annotate auth response

- lib/features/payment/payment_details_page.dart
- lib/features/payment/payment_method.dart
- lib/shared/json_schema_form.dart
- lib/shared/utils/text_input_util.dart
- pubspec.lock
- pubspec.yaml
- test/shared/utils/text_input_util_test.dart
closes https://github.com/TBD54566975/didpay/issues/79
https://github.com/TBD54566975/didpay/assets/125412902/765686dd-bf34-4823-9cfa-e77ae9985558
> feat: add input masking

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
Noticed dartfmt wasn't being used and creating diffs everywhere so I added it to vscode config. Wouldn't hurt to add a lint step but this is low hanging fruit.
> use dartfmt

- lib/features/currency/currency.dart
- lib/features/currency/payin.dart
- lib/features/currency/payout.dart
- lib/features/home/home_page.dart
- lib/features/home/transaction_details_page.dart
- lib/features/request/deposit_page.dart
- lib/features/request/review_request_page.dart
- lib/features/request/withdraw_page.dart
- lib/features/send/send.dart
- test/features/home/transaction_details_page_test.dart
- test/features/payment/review_request_page_test.dart
closes https://github.com/TBD54566975/didpay/issues/81
https://github.com/TBD54566975/didpay/assets/125412902/4769c0f3-0b51-43d9-a361-3dcaab519cee
https://github.com/TBD54566975/didpay/assets/125412902/3a9d69dc-e02d-4d98-95b3-ea786405fe16
> feat: add decimal padding hint

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- pubspec.lock
I think this step in the build is resetting the upgrade check back to what Flutter wants:
```sh
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
```
https://github.com/flutter/flutter/issues/137855
> chore: fix xcode project changes

- lib/features/account/account_did_page.dart
- lib/features/account/account_page.dart
- lib/features/account/account_vc_page.dart
- lib/features/currency/currency_modal.dart
- lib/features/currency/payin.dart
- lib/features/home/home_page.dart
- lib/features/home/transaction_details_page.dart
- lib/features/onboarding/agreement_page.dart
- lib/features/onboarding/country_page.dart
- lib/features/onboarding/welcome_page.dart
- lib/features/payment/payment_details_page.dart
- lib/features/payment/search_payment_methods_page.dart
- lib/features/payment/search_payment_types_page.dart
- lib/features/pfis/pfi_confirmation_page.dart
- lib/features/pfis/pfi_page.dart
- lib/features/request/deposit_page.dart
- lib/features/request/review_request_page.dart
- lib/features/request/withdraw_page.dart
- lib/features/send/send_did_page.dart
- lib/features/send/send_page.dart
- lib/features/wallets/wallet_selection_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- lib/shared/search_field.dart
- test/features/payment/payment_details_page_test.dart
closes https://github.com/TBD54566975/didpay/issues/95
> chore: refactor code style

- ios/ci_scripts/ci_post_clone.sh
for https://github.com/TBD54566975/didpay/issues/111
> using hermit in xcode cloud

- lib/features/home/transaction.dart
- lib/features/payin/payin.dart
- lib/features/payin/payin_details_page.dart
- lib/features/payment/review_payment_page.dart
- lib/features/payout/payout.dart
- lib/features/payout/payout_details_page.dart
- lib/features/remittance/remittance_country_page.dart
- lib/features/remittance/remittance_page.dart
- lib/features/send/send_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- test/features/remittance/remittance_page_test.dart
- test/features/send/send_page_test.dart
closes #92 
https://github.com/TBD54566975/didpay/assets/125412902/a5d30d46-2f97-4d51-b608-e13235421b32
https://github.com/TBD54566975/didpay/assets/125412902/c47d560f-4947-4c4f-a724-5cc5d1d89429
> feat: add remittance flow

- lib/config/config.dart
- lib/features/payin/deposit_page.dart
- lib/features/payout/withdraw_page.dart
- lib/features/remittance/remittance_page.dart
- lib/features/tbdex/tbdex_providers.dart
- test/features/payin/deposit_page_test.dart
- test/features/payout/withdraw_page_test.dart
- test/features/remittance/remittance_page_test.dart
> feat: get offerings from country

- lib/features/send/send_did_page.dart
- test/features/send/send_did_page_test.dart
closes https://github.com/TBD54566975/didpay/issues/127
> fix: remove disabled button in `SendDidPage`

- lib/features/home/home_page.dart
- lib/features/payin/deposit_page.dart
- lib/features/payin/payin_details_page.dart
- lib/features/payment/payment_state.dart
- lib/features/payment/review_payment_page.dart
- lib/features/payout/payout_details_page.dart
- lib/features/payout/withdraw_page.dart
- lib/features/remittance/remittance_country_page.dart
- lib/features/remittance/remittance_page.dart
- lib/features/tbdex/rfq_state.dart
- lib/features/tbdex/tbdex_providers.dart
- pubspec.lock
- pubspec.yaml
- test/features/payin/deposit_page_test.dart
- test/features/payin/payin_details_page_test.dart
- test/features/payment/review_payment_page_test.dart
- test/features/payout/payout_details_page_test.dart
- test/features/payout/withdraw_page_test.dart
- test/features/remittance/remittance_page_test.dart
part 1 of https://github.com/TBD54566975/didpay/issues/110
this pr just sends the rfq, a followup pr will address making sure a 202 is returned from a pfi and waiting to get a quote before showing `ReviewPaymentPage`
> feat: send rfq

- lib/features/account/account_page.dart
- lib/features/home/home_page.dart
- lib/features/home/transaction.dart
- lib/features/payin/deposit_page.dart
- lib/features/payin/payin_details_page.dart
- lib/features/payment/payment_confirmation_page.dart
- lib/features/payment/review_payment_page.dart
- lib/features/payout/payout_details_page.dart
- lib/features/payout/withdraw_page.dart
- lib/features/pfis/pfi_confirmation_page.dart
- lib/features/remittance/remittance_page.dart
- lib/features/send/send_confirmation_page.dart
- lib/features/storage/storage_service.dart
- lib/features/tbdex/tbdex_providers.dart
- this pr adds github issues to every written `TODO`
- any `TODO`s following this pr should adhere to the following [Flutter TODO format](https://dart.dev/tools/linter-rules/flutter_style_todos): 
```
// TODO(username): message, https://URL-to-issue
```
> chore: add issues to every `TODO`

- README.md
this pr updates the `README.md` along with a note to use `XCode 15.3` and `iOS 17.4` on the simulator
> chore: update `README`

- lib/features/tbdex/tbdex_providers.dart
- pubspec.lock
closes https://github.com/TBD54566975/didpay/issues/133
> fix: remove hardcoded did

- lib/features/payin/deposit_page.dart
- lib/features/payin/payin_details_page.dart
- lib/features/payment/payment_details.dart
- lib/features/payment/review_payment_page.dart
- lib/features/payout/payout_details_page.dart
- lib/features/payout/withdraw_page.dart
- lib/features/remittance/remittance_page.dart
- lib/features/tbdex/quote_notifier.dart
- lib/features/tbdex/rfq_state.dart
- lib/features/tbdex/tbdex.dart
- lib/features/tbdex/tbdex_providers.dart
- test/features/payin/deposit_page_test.dart
- test/features/payment/review_payment_page_test.dart
- test/features/payout/payout_details_page_test.dart
- test/features/payout/withdraw_page_test.dart
- test/features/remittance/remittance_page_test.dart
closes https://github.com/TBD54566975/didpay/issues/131
the quote coming back in the below screen recording is a stubbed quote response coming from a pfi
```
{
"body": {
"data": [
{
"data": {
"payin": {
"fee": "0.1",
"amount": "10",
"currencyCode": "USD"
},
"payout": {
"fee": "0.5",
"amount": "500",
"currencyCode": "MXN"
},
"expiresAt": "2024-05-04T00:48:25Z"
},
"metadata": {
"id": "quote_01hwxyryy3fkmrdyjbq5bp109a",
"to": "did:jwk:eyJrdHkiOiJPS1AiLCJjcnYiOiJFZDI1NTE5IiwieCI6IjV4Uzg1bHhvU0hJQ1hsTkxURDl2RkFsRGZqMXczRFRYSm1qdVVNcTA3U1kifQ",
"from": "did:jwk:eyJrdHkiOiJPS1AiLCJjcnYiOiJFZDI1NTE5IiwieCI6Ikh3dDd4YzBTWlVVUVR1MnNkV2M5Q3RNSG5kRFU4eEhWT3gtcVpKdHpHVmMifQ",
"kind": "quote",
"protocol": "1.0",
"createdAt": "2024-05-03T00:48:25Z",
"exchangeId": "rfq_01hwxyrwsae2kr7f64nwkpe40d"
}, …
```
> feat: poll for quote

- lib/features/payin/deposit_page.dart
- lib/features/payin/payin.dart
- lib/features/payment/review_payment_page.dart
- lib/features/payout/payout.dart
- lib/features/payout/withdraw_page.dart
- lib/features/remittance/remittance_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- lib/shared/fee_details.dart
- test/features/payin/payin_test.dart
- test/features/payment/review_payment_page_test.dart
- test/features/payout/payout_test.dart
- test/shared/fee_details_test.dart
closes https://github.com/TBD54566975/didpay/issues/143
https://github.com/TBD54566975/didpay/assets/125412902/8b2f01c3-9e40-40b5-8f65-b0ae2b407ddb
https://github.com/TBD54566975/didpay/assets/125412902/58927df6-b1ba-417b-8b7e-52be13eb4a07
https://github.com/TBD54566975/didpay/assets/125412902/9c21cf00-c1ec-447a-bf4b-2c8682200dd3
> feat: update fee details

- lib/features/tbdex/tbdex_providers.dart
- lib/main.dart
- pubspec.lock
- test/features/account/account_did_page_test.dart
- test/features/idv/idv_service_test.dart
- test/features/payment/review_payment_page_test.dart
- test/features/send/send_did_page_test.dart
- test/features/send/send_page_test.dart
this pr uses `DidDht` over `DidJwk` now that `web5-dart` can support `DidDht.create()`
> feat: use `did:dht`

- lib/features/did_qr/did_qr.dart
- lib/features/did_qr/did_qr_scan_page.dart
- lib/features/pfis/pfi_page.dart
- lib/features/send/send_did_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- test/features/send/send_did_page_test.dart
this pr moves the did qr code widgets and scanning logic into its own feature.
> chore: did qr feature

- lib/main.dart
follow-up fix for https://github.com/TBD54566975/didpay/pull/157
> fix: override `countriesProvider`

- lib/features/account/account_page.dart
- lib/features/app/app.dart
- lib/features/app/app_tabs.dart
- lib/features/payout/payout_details_page.dart
- lib/features/pfis/pfi_modal.dart
- lib/features/pfis/pfis_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
this pr adds basic pfi management in the `Account` tab, allowing one to add and remove pfis
https://github.com/TBD54566975/didpay/assets/125412902/9697f7d4-d80e-4885-a18d-16769d394749
> feat: add pfi management

- lib/features/send/send_details_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
this pr maintains consistency with the other details pages, especially the `AddPfiPage`
> fix: update `SendDetailsPage`

- lib/features/app/app.dart
- lib/features/pfis/add_pfi_page.dart
- lib/features/pfis/pfis_notifier.dart
- lib/features/pfis/pfis_page.dart
- lib/features/remittance/countries_notifier.dart
- lib/main.dart
- lib/shared/success_state.dart
this pr cleans up `main.dart` as well as loading pfis from `SharedPreferences` on start up
> chore: clean up

- lib/shared/utils/text_input_util.dart
- test/shared/utils/text_input_util_test.dart
closes https://github.com/TBD54566975/didpay/issues/101
> fix: regex to phone number input mask

- lib/features/kcc/kcc_consent_page.dart
- lib/features/kcc/kcc_retrieval_page.dart
- lib/features/kcc/kcc_webview_page.dart
- lib/features/payment/payment_details_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- updates the way that the kcc `ModalFlow` is started using `fullScreenDialog`
- adds cancel buttons in app bar of modal pages
- adds localized strings
> feat: update kcc modal

- lib/features/countries/countries_page.dart
- lib/features/kcc/kcc_consent_page.dart
- lib/features/payment/payment_details_page.dart
- lib/features/payment/payment_review_page.dart
- lib/features/pfis/add_pfi_page.dart
- lib/features/send/send_details_page.dart
- lib/features/wallets/wallet_selection_page.dart
- lib/shared/async/async_error_widget.dart
- lib/shared/header.dart
this pr adds a `Header` widget to cut out redundant code
> feat: add header widget

- lib/features/account/account_balance.dart
- lib/features/account/account_balance_display.dart
- lib/features/account/account_balance_notifier.dart
- lib/features/home/home_page.dart
- lib/features/send/send_page.dart
- lib/features/tbdex/tbdex_service.dart
- pubspec.lock
- test/features/app/app_tabs_test.dart
- test/features/app/app_test.dart
- test/features/home/home_page_test.dart
- test/features/send/send_page_test.dart
- test/helpers/mocks.dart
closes https://github.com/TBD54566975/didpay/issues/109
> feat: get pfi balance

- pubspec.lock
- pubspec.yaml
- test/features/account/account_page_test.dart
- test/features/app/app_tabs_test.dart
- test/features/app/app_test.dart
- test/features/countries/countries_notifier_test.dart
- test/features/countries/countries_page_test.dart
- test/features/feature_flags/feature_flags_notifier_test.dart
- test/features/feature_flags/lucid/lucid_offerings_page_test.dart
- test/features/home/home_page_test.dart
- test/features/payin/payin_test.dart
- test/features/payment/payment_amount_page_test.dart
- test/features/payment/payment_details_page_test.dart
- test/features/payment/payment_methods_page_test.dart
- test/features/payment/payment_review_page_test.dart
- test/features/payment/payment_types_page_test.dart
- test/features/payout/payout_test.dart
- test/features/pfis/pfis_notifier_test.dart
- test/features/send/send_details_page_test.dart
- test/features/send/send_page_test.dart
- test/helpers/test_data.dart
adds `TestData` to reduce duplicate code in tests
> chore: add test data

- lib/features/account/account_page.dart
- lib/features/currency/currency_dropdown.dart
- lib/features/dap/dap_form.dart
- lib/features/did/did_form.dart
- lib/features/did/did_qr_tabs.dart
- lib/features/payin/payin.dart
- lib/features/send/send_page.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- pubspec.lock
- pubspec.yaml
- test/features/pfis/pfis_add_page_test.dart
- test/helpers/test_data.dart
- adds `DapForm` which calls `Dap.parse()` on user input
- brings in `dap-dart` dependency
- other small dap/send changes
> feat: add `DapForm`

- lib/features/account/account_page.dart
- lib/features/dap/dap_form.dart
- lib/features/dap/dap_qr_tile.dart
- lib/features/did/did_form.dart
- lib/features/did/did_qr_tile.dart
- lib/features/payment/payment_details_page.dart
- lib/features/payment/payment_state.dart
- lib/features/send/send_page.dart
- lib/features/tbdex/tbdex_service.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- pubspec.lock
- uses `DapResolver` to resolve daps
- adds loading and error screens for dap resolution
- fetches offerings based on the `MoneyAddress` currency found when resolving the dap
https://github.com/TBD54566975/didpay/assets/125412902/d2b8cdbb-115a-4de2-b09a-5de69b94a08e
> feat: fetch offerings using dap

- ios/Runner/Info.plist
- lib/features/account/account_balance_card.dart
- lib/features/dap/dap_form.dart
- lib/features/did/did_form.dart
- lib/features/did/did_qr_tile.dart
- lib/features/payment/payment_amount_page.dart
- lib/features/payment/payment_details_page.dart
- lib/features/payment/payment_fee_details.dart
- lib/features/payment/payment_link_webview_page.dart
- lib/features/payment/payment_review_page.dart
- lib/features/payment/payment_state.dart
- lib/features/pfis/pfis_add_page.dart
- lib/features/pfis/pfis_service.dart
- lib/features/send/send_page.dart
- lib/features/tbdex/tbdex_service.dart
- test/shared/payment_fee_details_test.dart
- adds `PaymentLinkWebviewPage` to render webview for dap send payins
- update `DidForm` to send raw string to `SendPage`
- submits order after finishing successfully completing payment page
> feat: add `PaymentLinkWebviewPage`

- lib/features/account/account_balance_card.dart
- lib/features/account/account_page.dart
- lib/features/home/home_page.dart
- lib/shared/number/number_pad.dart
- starts the process of supporting larger text for accessibility
> feat: support larger text in `HomePage`

- lib/features/payment/payment_amount_page.dart
- lib/features/payment/payment_amount_state.dart
- lib/features/payment/payment_details_page.dart
- lib/features/payment/payment_details_state.dart
- lib/features/payment/payment_methods_page.dart
- lib/features/payment/payment_review_page.dart
- lib/features/payment/payment_state.dart
- lib/features/send/send_page.dart
- lib/features/tbdex/tbdex_service.dart
- test/features/home/home_page_test.dart
- test/features/payment/payment_amount_page_test.dart
adds back dap flow after recent `PaymentState` refactor https://github.com/TBD54566975/didpay/pull/218
> fix: add back dap flow

- lib/features/payment/payment_amount_state.dart
- lib/features/payment/payment_details_page.dart
- lib/features/payment/payment_details_state.dart
- lib/features/payment/payment_fee_details.dart
- lib/features/payment/payment_link_webview_page.dart
- lib/features/payment/payment_review_page.dart
- lib/features/payment/payment_state.dart
- lib/features/transaction/transaction.dart
- pubspec.lock
- test/features/payment/payment_review_page_test.dart
- test/helpers/test_data.dart
- updates `tbdex` dependency after https://github.com/TBD54566975/tbdex-dart/pull/47
- uses new fields in `Quote`
- sends proper rfq via `TbdexHttpClient`
- ensures payment details in `PaymentReviewPage` are properly rendered
> chore: update `tbdex-dart` dep

- lib/features/account/account_balance_card.dart
- lib/features/countries/countries_page.dart
- lib/features/home/home_page.dart
- lib/features/payment/payment_amount_page.dart
- lib/features/payment/payment_details_page.dart
- lib/features/send/send_page.dart
- lib/shared/next_button.dart
- test/features/payment/payment_amount_page_test.dart
fix payment methods not being passed through to `PaymentDetailsPage`
> fix: payment methods

- lib/features/pfis/pfi.dart
- lib/main.dart
- adds tbd pfi did `did:web:pfi.tbd.engineering` as the default pfi
> feat: add tbd pfi

- lib/features/pfis/pfis_notifier.dart
- prevent adding duplicate pfi in `PfisNotifier`
> fix: prevent adding duplicate pfis in `PfisNotifier`

- lib/features/account/account_page.dart
- lib/features/dap/dap_qr_tile.dart
- lib/features/home/home_page.dart
- lib/features/payment/payment_details_page.dart
- lib/features/payment/payment_state.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- lib/shared/json_schema_form.dart
- test/features/home/home_page_test.dart
- test/shared/json_schema_form_test.dart
- adds a `KCC -  issuance date` title for all issued vcs in `AccountPage`
- reroutes the `Get started` button in `HomePage` to go to `SendPage`
- removes auto-skip of `PaymentDetailsPage` to allow user to confirm payment details
- updates localized strings
> fix: many ui fixes

- lib/features/tbdex/tbdex_service.dart
- lib/features/transaction/transaction.dart
- lib/features/transaction/transaction_details_page.dart
- lib/features/transaction/transaction_tile.dart
- improves styling on snackbar for transaction status updates
- only renders exchanges that have a order message in them
- uses `Chip` for the transaction status display in `TransactionDetailsPage`
> feat: update transaction UI

- lib/features/account/account_page.dart
- lib/shared/modal/modal_remove_item.dart
allows users to copy their pfi's did and copy their credential jwts
> feat: add copy to `ModalRemoveItem`

- lib/features/did/did_provider.dart
- lib/features/did/did_qr_code_page.dart
- lib/features/did/did_qr_tabs.dart
- lib/features/did/did_storage_service.dart
- lib/features/vcs/vcs_notifier.dart
- lib/l10n/app_en.arb
- lib/l10n/app_localizations.dart
- lib/l10n/app_localizations_en.dart
- lib/main.dart
- lib/shared/confirm_dialog.dart
- test/features/app/app_tabs_test.dart
- test/features/app/app_test.dart
- test/features/home/home_page_test.dart
- test/features/payment/payment_amount_page_test.dart
- test/features/payment/payment_details_page_test.dart
- test/features/payment/payment_review_page_test.dart
- test/features/send/send_page_test.dart
- brings in ability to regenerate did in account settings
https://github.com/user-attachments/assets/1e317f65-f629-41d3-83d2-fa573fe36b72
> feat: regenerate did

- lib/features/did/did_qr_code_page.dart
- lib/features/did/did_storage_service.dart
- allows copying of `PortableDid` json for testing purposes, will be reverted in the future
> feat: temporarily allow portable did copying

- lib/features/dap/dap_qr_tile.dart
- lib/features/did/did_qr_code_page.dart
- lib/features/did/did_qr_tile.dart
- lib/features/transaction/transaction_tile.dart
- lib/shared/modal/modal_manage_item.dart
- lib/shared/snackbar/snackbar_service.dart
closes https://github.com/TBD54566975/didpay/issues/255
> feat: add snackbar service

- lib/features/account/account_balance_card.dart
- lib/features/dap/dap_qr_tile.dart
- lib/features/did/did_qr_tile.dart
- lib/features/home/home_page.dart
- lib/features/kcc/kcc_retrieval_page.dart
- lib/features/kcc/kcc_webview_page.dart
- lib/features/payment/payment_amount_page.dart
- lib/features/payment/payment_fetch_instructions_widget.dart
- lib/features/payment/payment_fetch_quote_widget.dart
- lib/features/transaction/transaction_tile.dart
- test/features/app/app_tabs_test.dart
- test/features/home/home_page_test.dart
- test/features/pfis/pfis_add_page_test.dart
- test/features/send/send_page_test.dart
this pr replaces all `Future.microtask()` with `Future.delayed(Duration.zero)`
> chore: remove `Future.microtask()` use

- lib/features/payment/payment_details_page.dart
- lib/features/vcs/vcs_service.dart
this pr adds `VcsService` to help remove the `web5` dependency in the `PaymentDetailsPage` widget
> feat: add `VcsService`

- lib/shared/json_schema_form.dart
- this pr fixes a UI bug where changing payout methods in `PaymentMethodsPage` after having focused on a text field causes the focus node to get stuck
> fix: focus bug when switching payment methods

- lib/features/dap/dap_state.dart
this pr fixes `DapState` to use the updated dap `pss` and `protocol` methods properly
> fix: update `DapState` 
